# Homebrew formula template for formwatch.
#
# This is a template, not a published tap: replace VERSION and the four
# SHA256 values (generated by the release workflow's SHA256SUMS asset)
# before submitting it to a tap. Both macOS targets are listed because the
# release workflow builds x86_64 and arm64 separately.
class Formwatch < Formula
  desc "Tests public-service forms for broken flows, accessibility, and lost input"
  homepage "https://github.com/voidstackloop/formwatch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/voidstackloop/formwatch/releases/download/v#{version}/formwatch-aarch64-apple-darwin.tar.gz"
      sha256 "REPLACE_WITH_AARCH64_MACOS_SHA256"
    else
      url "https://github.com/voidstackloop/formwatch/releases/download/v#{version}/formwatch-x86_64-apple-darwin.tar.gz"
      sha256 "REPLACE_WITH_X86_64_MACOS_SHA256"
    end
  end

  on_linux do
    url "https://github.com/voidstackloop/formwatch/releases/download/v#{version}/formwatch-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "REPLACE_WITH_X86_64_LINUX_SHA256"
  end

  def install
    bin.install "formwatch"
    # The authorized-use notice and third-party attributions.
    prefix.install_metafiles if respond_to?(:prefix)
  end

  test do
    assert_match "formwatch", shell_output("#{bin}/formwatch --help")
    assert_match "authorized", shell_output("#{bin}/formwatch legal")
  end
end
